//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSpeed1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int ID { get; set; }
        public System.DateTime BeginDate { get; set; }
        public int Device { get; set; }
        public int Problem { get; set; }
        public string Description { get; set; }
        public int Client { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Worker { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Devices Devices { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual TypesOfProblems TypesOfProblems { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
