//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSpeed1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistics
    {
        public int ID { get; set; }
        public int CompletedRequests { get; set; }
        public double AvgTimeToRequest { get; set; }
        public string MostPopularProblem { get; set; }
    }
}
